### ISSUE TITLE
[Sample Onboard Request] Excel-Add-in-Mail-Merge

### ISSUE THREAD

**Issue by XuanZhouMSFT** [OfficeDev/TeamsFx-Samples#1219]
**Owner:**
SiruiSun-MSFT

**ID:**
Excel-Add-in-Mail-Merge

**Title:**
Create an Excel Mail Merge Add-in

**Description:**
This sample demonstrates how to use the Microsoft Graph JavaScript SDK to send emails in Excel from Office Add-ins.

**Tags:**
"JS", "Excel", "SSO", "Graph", "Office Add-in"

**Time:**
10mins to run

**Configuration:**
Ready for local debug

**Thumbnail:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Mail-Merge/assets/taskpane.png

**(Optional) Demo GIF:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Mail-Merge/assets/sampleDemo.gif

**(Source code in this Repo) Source Code PR:**
In another repo

**(Source code NOT in this Repo) Sample URL:**
https://github.com/OfficeDev/Office-Samples/blob/main/Excel-Add-in-Mail-Merge/

**(Optional) Minimum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - minimum version

**(Optional) Maximum Teams Toolkit Version:**
Teams Toolkit version requirement to run the sample - maximum version

**Comment by summzhan** [comment]
Reviewed README file, suggest to make the following update:
1. In Prerequsites, add one item to install VS Code version 5.6.0+ (version that contains WXP features）：
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/f512e890-3e32-4d6f-97c2-f5b28c4b4c17)

2. Do not use M365 Toolkit now, since the rebranding thing is not finalized. Now use Teams Toolkit as the official name:
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/8b9ef027-a8f2-4323-8a4d-d1eaf2c64de1)

3. The command name should be consistent with the screenshot:
![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/113089977/2ef759d5-c06a-4701-8c00-1a8bbd268e09)

**Comment by hermanwenhe** [comment]
updated

**Comment by XuanZhouMSFT** [comment]
[like]  Xuan Zhou reacted to your message:
________________________________

**Comment by tecton** [comment]
The linked page of "Sideload Office Add-ins to Office on the web" has multiple sections that could be confusing to users to follow.
