### ISSUE TITLE
How do you a sample bot sso app to work in a group chat?

### ISSUE THREAD

**Issue by JasonGoemaat** [OfficeDev/TeamsFx-Samples#915]
I can't figure out how to get it to work.  Is there a way to get it to work in dev mode?    It seems like the default running of the app only works with the direct chat to the bot.  I would like to be able to send commands to the bot to have it report information to the whole team or group.  I wonder if it's something with how it always asks me to add it when opening my browser, but then it isn't available to add to a chat.   I was thinking I should be able to just `@mybot` from *any* chat to get it to help.

**Comment by yukun-dong** [comment]
Hi @JasonGoemaat , I'm afraid this is by design. Teams Bot SSO is only supported in one-on-one chat. 

![image](https://github.com/OfficeDev/TeamsFx-Samples/assets/25220706/07f96a75-bc64-474b-ba9f-079a0d863b3f)

Above image comes from https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-overview. You can check this doc for more details.
